# Project: librarian-runner
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = mapmakers5-runner_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"D:/Programme/Dev-Cpp/MinGW64/lib" -L"D:/Programme/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows -mwindows -mwindows
INCS     = -I"D:/Programme/Dev-Cpp/MinGW64/include" -I"D:/Programme/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Programme/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Programme/Dev-Cpp/MinGW64/include" -I"D:/Programme/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Programme/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Programme/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = librarian-runner.exe
CXXFLAGS = $(CXXINCS) -mwindows
CFLAGS   = $(INCS) -mwindows
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

mapmakers5-runner_private.res: mapmakers5-runner_private.rc 
	$(WINDRES) -i mapmakers5-runner_private.rc --input-format=rc -o mapmakers5-runner_private.res -O coff 

