-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| --
-- ||||                                CMS                               |||| --
-- ||||                    --------------------------                    |||| --
-- ||||                           Loader Script                          |||| --
-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| --

-- This is the loader script for a CMS multiplayer map.
-- It needs to pe imported as mapscript.lua and localmapscript.lua in the
-- map folder or using the map editor's "expert mode".
--
-- YOU DO NOT EDIT THIS FILE!!

-- ========================================================================== --

IS_LOCAL = GUI ~= nil;
CMS_PATH = "maps/development/cms/";
Script.Load(CMS_PATH.. "s6communitylib/lua/loader.lua");

assert(Lib.SettlementMultiplayer ~= nil, "SettlementMultiplayer module not found!");
if Lib.SettlementMultiplayer then
    Lib.Loader.PushPath(CMS_PATH);
    local MapName = Framework.GetCurrentMapName();
    Script.Load("maps/externalmap/" .. MapName:lower() .. "/cms_imports.lua");
    if IS_LOCAL then
        Script.Load(CMS_PATH.. "localmapscript.lua");
    else
        Script.Load(CMS_PATH.. "mapscript.lua");
    end
end

