-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| --
-- ||||                                CMS                               |||| --
-- ||||                    --------------------------                    |||| --
-- ||||                       Internal Local Script                      |||| --
-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| --

-- This is the internal local script file für a CMS multiplayer map.
-- DO NOT EDIT THIS FILE!

-- ========================================================================== --

-- Default modules if user didn't include any
Lib.Require("core/Core");
Lib.Require("module/mode/SettlementMultiplayer");

-- ========================================================================== --

function Mission_LocalOnMapStart()
    local RuleSet = GetRuleDefinition();
    if RuleSet and RuleSet.Local and RuleSet.Local.OnGameStart then
        RuleSet.Local.OnGameStart(RuleSet);
    end
end

function GameCallback_Lib_LoadingFinished()
    local RuleSet = GetRuleDefinition();
    if RuleSet and RuleSet.Local and RuleSet.Local.OnSessionStart then
        RuleSet.Local.OnSessionStart(RuleSet);
    end
end

function Mission_LocalVictory()
end

