-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| --
-- ||||                                CMS                               |||| --
-- ||||                    --------------------------                    |||| --
-- ||||                      Internal Global Script                      |||| --
-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| --

-- This is the internal global script file für a CMS multiplayer map.
-- DO NOT EDIT THIS FILE!

-- ========================================================================== --

-- Default modules if user didn't include any
Lib.Require("core/Core");
Lib.Require("module/mode/SettlementMultiplayer");

-- ========================================================================== --

function Mission_FirstMapAction()
    if Framework.IsNetworkGame() ~= true then
        Startup_Player();
        Startup_StartGoods();
        Startup_Diplomacy();
    end
    PrepareLibrary();

    local RuleSet = GetRuleDefinition();
    if RuleSet and RuleSet.Global and RuleSet.Global.OnGameStart then
        RuleSet.Global.OnGameStart(RuleSet);
    end
end

function Mission_InitPlayers()
end

function Mission_SetStartingMonth()
end

function Mission_InitMerchants()
end

function GameCallback_Lib_LoadingFinished()
    Logic.SetMonthOffset(3);

    local RuleSet = GetRuleDefinition();
    if RuleSet and RuleSet.Global and RuleSet.Global.OnSessionStart then
        RuleSet.Global.OnSessionStart(RuleSet);
    end
end

