#!/bin/bash

# build architect
cd java/Architect
rm S6CommunityLib.jar
mvn clean package -Dmaven.test.skip=true
cp target/S6CommunityLib.jar .
cd ../..

# build release
rm var/release/S6CommunityLib.exe
rm var/release/s6communitylib.zip
rm -rf var/release/s6communitylib
mkdir -p var/release/s6communitylib/java/builder/config
mkdir -p var/release/s6communitylib/prebuild/library
mkdir -p var/release/s6communitylib/prebuild/single
cd java/Architect
java -jar S6CommunityLib.jar -l ../../var/release/s6communitylib/prebuild/library ../../exe/officialloadorder.txt
java -jar S6CommunityLib.jar -s ../../var/release/s6communitylib/prebuild/single ../../exe/officialloadorder.txt
cp -r ../../api ../../var/release/s6communitylib
cp -r ../../lua ../../var/release/s6communitylib
cp config/config.json ../../var/release/s6communitylib/java/builder/config
cp S6CommunityLib.jar ../../var/release/s6communitylib/java/builder
cp ../runner/librarian-runner.exe ../../var/release/s6communitylib/java/builder/S6CommunityLib.exe
cp -r D:/Programme/BellSoft/jdk8u275-full ../../var/release/s6communitylib/java/jre
cp ../../instructions_de.md ../../var/release/s6communitylib
cp ../../instructions_en.md ../../var/release/s6communitylib
cp ../../license.md ../../var/release/s6communitylib
cp ../../changelog.md ../../var/release/s6communitylib
cd ../..

# build documentation
lua lua/tools/ldoc/ldoc.lua -d var/release/s6communitylib/doc api/de/s6communitylib
cd exe
lua docbuilder.lua
cd ..

# zip release
cd var/release
zip -r s6communitylib.zip s6communitylib
cd ../..

# compile installer
ISCC.exe "exe\wizard.iss" #1>/dev/null

echo "Done!"