#!/bin/bash

mkdir release 2> /dev/null
rm -rf release/* 2> /dev/null

lua manager.lua -b -o "exe/officialloadorder.txt"

cp -r var/libertica release
cp changelog.md release
cp license.md release
cp -r api release && mv release/api release/libertica_api

lua manager.lua -b -s -o "exe/officialloadorder.txt"
mkdir -p release/single
cp -r "var/qsb.lua" "release/single/qsb.lua"
cp -r "var/localmapscript.lua" "release/single/localmapscript.lua"
cp -r "var/mapscript.lua" "release/single/mapscript.lua"

mkdir -p release/tools/builder/lua
cp readme_release.md release && mv release/readme_release.md release/readme.md
cp instructions_de.md release
cp instructions_en.md release
cp loadersf.lua release/tools/builder/lua

cp -r D:/Programme/BellSoft/jdk8u275-full release/jre

mkdir -p release/tools/builder/config
mkdir -p release/tools/builder/script
cp java/Librarian/target/Librarian.jar release/tools/builder
cp java/Librarian/run/librarian-runner/librarian-runner release/tools/builder/Librarian.exe
cp -r java/Librarian/config/config.json release/tools/builder/config
cp -r java/Librarian/script/update.bat release/tools/builder/script

exe/builddoc #&>/dev/null